spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Teste novamente  oi"
  default-value: "Mundo Prod"